const ayurvedicHerbs = [
    {
      id: 1,
      imageUrl: "https://m.media-amazon.com/images/I/51GdywOgOCL._AC_UF1000,1000_QL80_.jpg",
      name: "Ashwagandha",
      rarity: "Common",
      species: "Withania somnifera",
      information: "Ashwagandha is an adaptogen that helps the body manage stress. It is also known for its ability to enhance energy levels, improve concentration, and promote overall wellness. Traditionally used in Ayurvedic medicine, it is believed to have anti-inflammatory and antioxidant properties.",
      pricePer100gm: 150,
    },
    {
      id: 2,
      imageUrl: "https://www.starhealth.in/blog/wp-content/uploads/2023/08/Tulsi-leaves.png",
      name: "Tulsi",
      rarity: "Common",
      species: "Ocimum sanctum",
      information: "Also known as holy basil, Tulsi is revered for its medicinal properties and is often used in herbal teas. It has anti-inflammatory, antioxidant, and antibacterial properties, making it effective in treating respiratory conditions and reducing stress.",
      pricePer100gm: 100,
    },
    {
      id: 3,
      imageUrl: "https://5.imimg.com/data5/BJ/HI/NV/SELLER-3338118/turmeric-extract-95-curcuminoid-500x500.png",
      name: "Turmeric",
      rarity: "Common",
      species: "Curcuma longa",
      information: "Turmeric contains curcumin, a powerful anti-inflammatory compound. It is used in various culinary dishes and is known for its health benefits, including improved brain function, reduced risk of heart disease, and enhanced immune response.",
      pricePer100gm: 80,
    },
    {
      id: 4,
      imageUrl: "https://m.media-amazon.com/images/I/51scUMNI+jL._AC_UF1000,1000_QL80_.jpg",
      name: "Neem",
      rarity: "Common",
      species: "Azadirachta indica",
      information: "Neem is known for its antibacterial and antifungal properties. It is often used in skincare products and traditional medicine to treat various ailments, including skin infections, dental issues, and digestive problems.",
      pricePer100gm: 120,
    },
    {
      id: 5,
      imageUrl: "https://healthybuddha.in/image/cache/catalog/brahmi-leaves-500x515.jpg",
      name: "Brahmi",
      rarity: "Common",
      species: "Bacopa monnieri",
      information: "Brahmi is known for its cognitive-enhancing effects. It is used to improve memory, concentration, and overall brain function. It also has calming properties that help reduce anxiety and stress.",
      pricePer100gm: 200,
    },
    {
      id: 6,
      imageUrl: "https://m.media-amazon.com/images/S/assets.wholefoodsmarket.com/PIE/product/56eb1d21362af611007e72d7_365_-ginger-root.3._FMwebp__SR600,600_.jpg",
      name: "Ginger",
      rarity: "Common",
      species: "Zingiber officinale",
      information: "Ginger is widely used for its digestive benefits and is effective in alleviating nausea and motion sickness. It also has anti-inflammatory properties and can help relieve pain and soreness.",
      pricePer100gm: 70,
    },
    {
      id: 7,
      imageUrl: "https://zamaorganics.com/cdn/shop/files/Untitleddesign-2024-01-09T141504.289.png?v=1704789954",
      name: "Amla",
      rarity: "Common",
      species: "Phyllanthus emblica",
      information: "Amla is rich in Vitamin C and antioxidants, making it an excellent choice for boosting immunity and promoting skin health. It is also used in hair care products for its nourishing properties.",
      pricePer100gm: 180,
    },
    {
      id: 8,
      imageUrl: "https://images.squarespace-cdn.com/content/v1/626738a3ef46ac6401f0378a/1690303579176-CKQB2CGN773ZSPRE8I3D/cardamom+pods.png?format=1500w",
      name: "Cardamom",
      rarity: "Common",
      species: "Elettaria cardamomum",
      information: "Cardamom is used both as a spice and for its health benefits. It aids digestion, has antioxidant properties, and is believed to help in managing blood pressure and cholesterol levels.",
      pricePer100gm: 300,
    },
    {
      id: 9,
      imageUrl: "https://img.freepik.com/premium-photo/variety-nature-chinese-cinnamon-bark-type-herb-cinnamomum-cassia-form-popular-life_1020495-22599.jpg",
      name: "Cinnamon",
      rarity: "Common",
      species: "Cinnamomum verum",
      information: "Cinnamon is known for its anti-inflammatory and antioxidant properties. It can help regulate blood sugar levels and is often used in traditional medicine for digestive health.",
      pricePer100gm: 250,
    },
    {
      id: 10,
      imageUrl: "https://media.istockphoto.com/id/177293978/photo/liquorice-root.jpg?s=612x612&w=0&k=20&c=2oyrFHUj-7vflao2HYc8vgLWauixNf_6awKmDvsMl_U=",
      name: "Licorice",
      rarity: "Common",
      species: "Glycyrrhiza glabra",
      information: "Licorice root is used for soothing sore throats and digestive issues. It has anti-inflammatory and immune-boosting properties, making it beneficial for respiratory health.",
      pricePer100: 160,
    }
  ]
  export default ayurvedicHerbs;